title: Default
icon: blank

accept:
  extension: jpg, png, mp4

fields:
  caption:
    label: Caption
    type: textarea
    size: small
    help: '(optional)'
    width: 1/2
  display:
    label: 'Show/hide'
    type: toggle
    text: 
      - "hide"
      - "show"
    default: true
    width: 1/4